SELECT t2.MEMBER_NAME, t1.REVIEW_TEXT, DATE_FORMAT(t1.REVIEW_DATE, '%Y-%m-%d')
FROM REST_REVIEW AS `t1`
JOIN (
    SELECT R.MEMBER_ID, M.MEMBER_NAME, RANK() OVER(ORDER BY count DESC) AS RANKING
    FROM (
        SELECT *, COUNT(MEMBER_ID) AS `count`
        FROM REST_REVIEW
        GROUP BY MEMBER_ID) AS `R`
    JOIN MEMBER_PROFILE AS `M` ON R.MEMBER_ID = M.MEMBER_ID) AS `t2`
ON t1.MEMBER_ID = t2.MEMBER_ID
WHERE t2.RANKING = 1
ORDER BY t1.REVIEW_DATE;