SELECT t1.AUTHOR_ID, t2.AUTHOR_NAME, t1.CATEGORY, SUM(t1.PRICE*t3.SALES) AS `TOTAL_SALES` FROM BOOK AS `t1` JOIN AUTHOR AS `t2` ON t1.AUTHOR_ID = t2.AUTHOR_ID
JOIN BOOK_SALES AS `t3` ON t1.BOOK_ID = t3.BOOK_ID WHERE t3.SALES_DATE LIKE '2022-01%' GROUP BY t2.AUTHOR_ID, t2.AUTHOR_NAME, t1.CATEGORY ORDER BY AUTHOR_ID, CATEGORY DESC
;